module.exports = {
  ERROR_NEW_MOVIE: 'ERROR_NEW_MOVIE',
  REQUEST_NEW_MOVIE: 'REQUEST_NEW_MOVIE',
  RECIEVE_NEW_MOVIE: 'RECIEVE_NEW_MOVIE',
  RESET_NEW_MOVIE: 'RESET_NEW_MOVIE',
  OMDB_URL: 'http://www.omdbapi.com/'
};
